In [2]:
import pandas as pd

In [3]:
csv = "player_traditional_stats_20-21.csv"

In [7]:
df = pd.read_csv(csv, parse_dates=True)
df.drop(columns=["season_id","player_name","team_id",])

,player_id,team_id,team_abbreviation,age,gp,w,l,w_pct,min,fgm,...,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,cfid,cfparams
0,Aaron Gordon,1610612743,DEN,25.0,50,29,21,0.580,1383.780000,231,...,409,314,95,156,124,150,115,17,5,"203932,1610612743"
1,Aaron Holiday,1610612754,IND,24.0,66,30,36,0.455,1176.086667,170,...,432,325,201,203,218,244,178,29,5,"1628988,1610612754"
2,Aaron Nesmith,1610612738,BOS,21.0,46,22,24,0.478,668.731667,78,...,237,301,354,343,258,347,245,29,5,"1630174,1610612738"
3,Abdel Nader,1610612756,PHX,27.0,24,16,8,0.667,355.250000,57,...,149,152,328,367,162,380,245,29,5,"1627846,1610612756"
4,Adam Mokoka,1610612741,CHI,22.0,14,3,11,0.214,56.178333,7,...,39,34,519,500,262,510,245,29,5,"1629690,1610612741"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Yogi Ferrell,1610612746,LAC,28.0,10,4,6,0.400,136.981667,20,...,136,76,421,447,235,447,245,29,5,"1627812,1610612746"
536,Yuta Watanabe,1610612761,TOR,26.0,50,24,26,0.480,722.823333,79,...,198,219,334,343,354,320,245,29,5,"1629139,1610612761"
537,Zach LaVine,1610612741,CHI,26.0,58,26,32,0.448,2033.626667,569,...,526,465,32,13,266,24,115,29,5,"203897,1610612741"
538,Zeke Nnaji,1610612743,DEN,20.0,42,30,12,0.714,397.278333,50,...,170,135,414,380,424,396,245,29,5,"1630192,1610612743"
539,Zion Williamson,1610612740,NOP,20.0,61,29,32,0.475,2025.890000,634,...,540,457,6,10,107,16,33,29,5,"1629627,1610612740"